import { Test, Package } from './types';

export const TESTS: Test[] = [
  {
    id: 'lipid-profile',
    name: 'Lipid Profile',
    category: 'Heart Health',
    mrp: 900,
    offerPrice: 599,
    description: 'Measures cholesterol and triglycerides to assess heart disease risk.',
    fastingRequired: true,
    homeCollection: true,
  },
  {
    id: 'liver-profile',
    name: 'Liver Profile (LFT)',
    category: 'Liver Health',
    mrp: 900,
    offerPrice: 599,
    description: 'Evaluates liver function by measuring enzymes and proteins.',
    fastingRequired: true,
    homeCollection: true,
  },
  {
    id: 'kidney-profile',
    name: 'Kidney Profile (KFT)',
    category: 'Kidney Health',
    mrp: 900,
    offerPrice: 599,
    description: 'Checks kidney function and electrolyte balance.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'creatinine',
    name: 'Creatinine',
    category: 'Kidney Health',
    mrp: 200,
    offerPrice: 169,
    description: 'Specific test for kidney filtration efficiency.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'sgpt',
    name: 'SGPT (ALT)',
    category: 'Liver Health',
    mrp: 200,
    offerPrice: 149,
    description: 'Liver enzyme test to detect liver damage.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'sgot',
    name: 'SGOT (AST)',
    category: 'Liver Health',
    mrp: 200,
    offerPrice: 159,
    description: 'Enzyme test for liver and heart health.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'cbc',
    name: 'Complete Blood Count (CBC)',
    category: 'General Health',
    mrp: 300,
    offerPrice: 249,
    description: 'Screens for anemia, infection, and other blood disorders.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'vitamin-b12',
    name: 'Vitamin B12',
    category: 'Vitamins',
    mrp: 1350,
    offerPrice: 1049,
    description: 'Measures levels of Vitamin B12 for nerve and blood health.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'vitamin-d',
    name: 'Vitamin D (25-OH)',
    category: 'Vitamins',
    mrp: 1650,
    offerPrice: 1301,
    description: 'Essential for bone health and immune function.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'anti-ccp',
    name: 'Anti CCP',
    category: 'Arthritis',
    mrp: 2150,
    offerPrice: 1999,
    description: 'Used to diagnose rheumatoid arthritis.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'anti-tpo',
    name: 'Anti TPO',
    category: 'Thyroid',
    mrp: 2000,
    offerPrice: 1799,
    description: 'Detects autoimmune thyroid disorders.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'urine-routine',
    name: 'Urine Routine',
    category: 'General Health',
    mrp: 250,
    offerPrice: 199,
    description: 'Screens for UTI, kidney issues, and diabetes.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'urine-micro',
    name: 'Urine Microalbumin',
    category: 'Kidney Health',
    mrp: 600,
    offerPrice: 449,
    description: 'Early marker for kidney damage in diabetics.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'widal',
    name: 'Widal Test',
    category: 'Infections',
    mrp: 300,
    offerPrice: 249,
    description: 'Diagnostic test for typhoid fever.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'urea',
    name: 'Urea',
    category: 'Kidney Health',
    mrp: 200,
    offerPrice: 179,
    description: 'Measures nitrogen waste in blood.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'tsh',
    name: 'TSH',
    category: 'Thyroid',
    mrp: 350,
    offerPrice: 299,
    description: 'Primary screening for thyroid function.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'thyroid-profile',
    name: 'Thyroid Profile (T3, T4, TSH)',
    category: 'Thyroid',
    mrp: 700,
    offerPrice: 599,
    description: 'Comprehensive thyroid function assessment.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'hba1c',
    name: 'HbA1c',
    category: 'Diabetes',
    mrp: 700,
    offerPrice: 599,
    description: 'Average blood sugar levels over 3 months.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'fbs',
    name: 'Fasting Blood Sugar (FBS)',
    category: 'Diabetes',
    mrp: 120,
    offerPrice: 69,
    description: 'Measures blood glucose after fasting.',
    fastingRequired: true,
    homeCollection: true,
  },
  {
    id: 'ppbs',
    name: 'Post Prandial Blood Sugar (PPBS)',
    category: 'Diabetes',
    mrp: 120,
    offerPrice: 69,
    description: 'Measures blood glucose 2 hours after a meal.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'ana',
    name: 'ANA (Antinuclear Antibody)',
    category: 'Autoimmune',
    mrp: 1599,
    offerPrice: 1399,
    description: 'Screens for autoimmune diseases like Lupus.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'psa',
    name: 'PSA (Prostate Specific Antigen)',
    category: 'Cancer Screening',
    mrp: 1000,
    offerPrice: 1000,
    description: 'Screens for prostate issues in men.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'beta-hcg',
    name: 'Beta HCG',
    category: 'Pregnancy',
    mrp: 1500,
    offerPrice: 1300,
    description: 'Pregnancy confirmation and monitoring.',
    fastingRequired: false,
    homeCollection: true,
  },
  {
    id: 'tpo',
    name: 'TPO Antibody',
    category: 'Thyroid',
    mrp: 1150,
    offerPrice: 1150,
    description: 'Specific antibody test for thyroid health.',
    fastingRequired: false,
    homeCollection: true,
  },
];

export const WELLNESS_PACKAGE: Package = {
  id: 'wellness-health-package',
  name: 'Wellness Health Package',
  price: 2800,
  isBestValue: true,
  tests: [
    'Lipid Profile',
    'LFT',
    'KFT',
    'Vitamin B12',
    'Vitamin D',
    'HbA1c',
    'Iron',
    'CBC',
    'Calcium',
    'Creatinine',
    'Uric Acid',
    'Urine',
    'Thyroid Profile',
    'FBS',
  ],
  description: 'Our most comprehensive health checkup covering all vital organs and vitamin levels.',
};
